'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class loginsetds
    Inherits DataSet
    
    Private tableTableUser As TableUserDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TableUser")) Is Nothing) Then
                Me.Tables.Add(New TableUserDataTable(ds.Tables("TableUser")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TableUser As TableUserDataTable
        Get
            Return Me.tableTableUser
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As loginsetds = CType(MyBase.Clone,loginsetds)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TableUser")) Is Nothing) Then
            Me.Tables.Add(New TableUserDataTable(ds.Tables("TableUser")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTableUser = CType(Me.Tables("TableUser"),TableUserDataTable)
        If (Not (Me.tableTableUser) Is Nothing) Then
            Me.tableTableUser.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "loginsetds"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/loginsetds.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTableUser = New TableUserDataTable
        Me.Tables.Add(Me.tableTableUser)
    End Sub
    
    Private Function ShouldSerializeTableUser() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TableUserRowChangeEventHandler(ByVal sender As Object, ByVal e As TableUserRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TableUserDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnID As DataColumn
        
        Private columnpassword As DataColumn
        
        Private columnusername As DataColumn
        
        Friend Sub New()
            MyBase.New("TableUser")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property IDColumn As DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        Friend ReadOnly Property passwordColumn As DataColumn
            Get
                Return Me.columnpassword
            End Get
        End Property
        
        Friend ReadOnly Property usernameColumn As DataColumn
            Get
                Return Me.columnusername
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TableUserRow
            Get
                Return CType(Me.Rows(index),TableUserRow)
            End Get
        End Property
        
        Public Event TableUserRowChanged As TableUserRowChangeEventHandler
        
        Public Event TableUserRowChanging As TableUserRowChangeEventHandler
        
        Public Event TableUserRowDeleted As TableUserRowChangeEventHandler
        
        Public Event TableUserRowDeleting As TableUserRowChangeEventHandler
        
        Public Overloads Sub AddTableUserRow(ByVal row As TableUserRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTableUserRow(ByVal password As String, ByVal username As String) As TableUserRow
            Dim rowTableUserRow As TableUserRow = CType(Me.NewRow,TableUserRow)
            rowTableUserRow.ItemArray = New Object() {Nothing, password, username}
            Me.Rows.Add(rowTableUserRow)
            Return rowTableUserRow
        End Function
        
        Public Function FindByID(ByVal ID As Integer) As TableUserRow
            Return CType(Me.Rows.Find(New Object() {ID}),TableUserRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TableUserDataTable = CType(MyBase.Clone,TableUserDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TableUserDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnID = Me.Columns("ID")
            Me.columnpassword = Me.Columns("password")
            Me.columnusername = Me.Columns("username")
        End Sub
        
        Private Sub InitClass()
            Me.columnID = New DataColumn("ID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID)
            Me.columnpassword = New DataColumn("password", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnpassword)
            Me.columnusername = New DataColumn("username", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnusername)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnID}, true))
            Me.columnID.AutoIncrement = true
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
        End Sub
        
        Public Function NewTableUserRow() As TableUserRow
            Return CType(Me.NewRow,TableUserRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TableUserRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TableUserRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TableUserRowChangedEvent) Is Nothing) Then
                RaiseEvent TableUserRowChanged(Me, New TableUserRowChangeEvent(CType(e.Row,TableUserRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TableUserRowChangingEvent) Is Nothing) Then
                RaiseEvent TableUserRowChanging(Me, New TableUserRowChangeEvent(CType(e.Row,TableUserRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TableUserRowDeletedEvent) Is Nothing) Then
                RaiseEvent TableUserRowDeleted(Me, New TableUserRowChangeEvent(CType(e.Row,TableUserRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TableUserRowDeletingEvent) Is Nothing) Then
                RaiseEvent TableUserRowDeleting(Me, New TableUserRowChangeEvent(CType(e.Row,TableUserRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTableUserRow(ByVal row As TableUserRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TableUserRow
        Inherits DataRow
        
        Private tableTableUser As TableUserDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTableUser = CType(Me.Table,TableUserDataTable)
        End Sub
        
        Public Property ID As Integer
            Get
                Return CType(Me(Me.tableTableUser.IDColumn),Integer)
            End Get
            Set
                Me(Me.tableTableUser.IDColumn) = value
            End Set
        End Property
        
        Public Property password As String
            Get
                Try 
                    Return CType(Me(Me.tableTableUser.passwordColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTableUser.passwordColumn) = value
            End Set
        End Property
        
        Public Property username As String
            Get
                Try 
                    Return CType(Me(Me.tableTableUser.usernameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTableUser.usernameColumn) = value
            End Set
        End Property
        
        Public Function IspasswordNull() As Boolean
            Return Me.IsNull(Me.tableTableUser.passwordColumn)
        End Function
        
        Public Sub SetpasswordNull()
            Me(Me.tableTableUser.passwordColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsusernameNull() As Boolean
            Return Me.IsNull(Me.tableTableUser.usernameColumn)
        End Function
        
        Public Sub SetusernameNull()
            Me(Me.tableTableUser.usernameColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TableUserRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TableUserRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TableUserRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TableUserRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
